"""Migrations must match the models.

Autogenerated migrations drift silently: someone edits `models.py`, the tests
pass because the test schema is built with `create_all`, and the deployed
database is then missing a column. This applies the migrations to a throwaway
database and asks alembic whether anything is still outstanding.
"""

from __future__ import annotations

from pathlib import Path
from urllib.parse import urlsplit, urlunsplit

import pytest

MIGRATION_DB = "scribe_migrationcheck"


@pytest.fixture
def fresh_database(db_settings):
    """An empty database, dropped and recreated for this test."""
    import psycopg

    parts = urlsplit(db_settings.database_url)
    admin = urlunsplit(parts._replace(scheme="postgresql", path="/postgres"))
    with psycopg.connect(admin, autocommit=True, connect_timeout=5) as conn:
        conn.execute(f'DROP DATABASE IF EXISTS "{MIGRATION_DB}" WITH (FORCE)')
        conn.execute(f'CREATE DATABASE "{MIGRATION_DB}"')

    url = urlunsplit(parts._replace(path=f"/{MIGRATION_DB}"))
    yield url

    with psycopg.connect(admin, autocommit=True, connect_timeout=5) as conn:
        conn.execute(f'DROP DATABASE IF EXISTS "{MIGRATION_DB}" WITH (FORCE)')


def _config(url: str):
    from alembic.config import Config

    root = Path(__file__).resolve().parents[1]
    config = Config(str(root / "alembic.ini"))
    config.set_main_option("script_location", str(root / "alembic"))
    config.set_main_option("sqlalchemy.url", url)
    return config


def test_upgrade_produces_a_schema_matching_the_models(fresh_database):
    from alembic.util.exc import AutogenerateDiffsDetected

    from alembic import command

    config = _config(fresh_database)
    command.upgrade(config, "head")
    try:
        command.check(config)
    except AutogenerateDiffsDetected as exc:
        pytest.fail(
            "models.py and the migrations disagree — generate a new revision:\n"
            f"  uv run alembic revision --autogenerate -m 'describe change'\n\n{exc}"
        )


def test_downgrade_to_base_is_reversible(fresh_database):
    from alembic import command

    config = _config(fresh_database)
    command.upgrade(config, "head")
    command.downgrade(config, "base")
    command.upgrade(config, "head")
