"""Migrations must match the models.

Autogenerated migrations drift silently: someone edits `models.py`, the tests
pass because the test schema is built with `create_all`, and the deployed
database is then missing a column. This applies the migrations to a throwaway
database and asks alembic whether anything is still outstanding.
"""

from __future__ import annotations

from pathlib import Path
from urllib.parse import urlsplit, urlunsplit

import pytest

MIGRATION_DB = "scribe_test_migrationcheck"


@pytest.fixture
def fresh_database(db_settings):
    """An empty database, dropped and recreated for this test."""
    import psycopg

    parts = urlsplit(db_settings.database_url)
    admin = urlunsplit(parts._replace(scheme="postgresql", path="/postgres"))
    with psycopg.connect(admin, autocommit=True, connect_timeout=5) as conn:
        conn.execute(f'DROP DATABASE IF EXISTS "{MIGRATION_DB}" WITH (FORCE)')
        conn.execute(f'CREATE DATABASE "{MIGRATION_DB}"')

    url = urlunsplit(parts._replace(path=f"/{MIGRATION_DB}"))
    # Guard against ever running `downgrade base` on real data again.
    assert MIGRATION_DB.startswith("scribe_test")
    yield url

    with psycopg.connect(admin, autocommit=True, connect_timeout=5) as conn:
        conn.execute(f'DROP DATABASE IF EXISTS "{MIGRATION_DB}" WITH (FORCE)')


def _config(url: str):
    from alembic.config import Config

    root = Path(__file__).resolve().parents[1]
    config = Config(str(root / "alembic.ini"))
    config.set_main_option("script_location", str(root / "alembic"))
    config.set_main_option("sqlalchemy.url", url)
    return config


def test_env_py_honours_an_explicit_url():
    """Regression: env.py used to override the caller's URL unconditionally.

    That silently redirected these tests at the development database, where
    `downgrade base` dropped every table. The URL a caller sets must win.
    """
    from alembic import context  # noqa: F401  (import proves the module loads)

    url = "postgresql+psycopg://someone:secret@example.invalid:5432/scribe_test_x"
    config = _config(url)
    assert config.get_main_option("sqlalchemy.url") == url

    env = (Path(__file__).resolve().parents[1] / "alembic" / "env.py").read_text()
    assert 'if not config.get_main_option("sqlalchemy.url", None):' in env, (
        "env.py must only fall back to settings when no URL was configured"
    )


def test_upgrade_produces_a_schema_matching_the_models(fresh_database):
    from alembic.util.exc import AutogenerateDiffsDetected

    from alembic import command

    config = _config(fresh_database)
    command.upgrade(config, "head")
    try:
        command.check(config)
    except AutogenerateDiffsDetected as exc:
        pytest.fail(
            "models.py and the migrations disagree — generate a new revision:\n"
            f"  uv run alembic revision --autogenerate -m 'describe change'\n\n{exc}"
        )


def test_downgrade_to_base_is_reversible(fresh_database):
    from alembic import command

    config = _config(fresh_database)
    command.upgrade(config, "head")
    command.downgrade(config, "base")
    command.upgrade(config, "head")
