"""jobs and job_events

Revision ID: 4c453369a97a
Revises: 
Create Date: 2026-08-26 22:02:19.742602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c453369a97a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('source_name', sa.String(length=512), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('source_bytes', sa.Integer(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('claimed_by', sa.String(length=128), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('output_dir', sa.Text(), nullable=True),
    sa.Column('asr_backend', sa.String(length=32), nullable=True),
    sa.Column('asr_model', sa.String(length=256), nullable=True),
    sa.Column('diar_model', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('attempts >= 0', name='ck_jobs_attempts'),
    sa.CheckConstraint('progress >= 0 AND progress <= 1', name='ck_jobs_progress'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_pending', 'jobs', ['created_at'], unique=False, postgresql_where=sa.text("state = 'pending'"))
    op.create_index(op.f('ix_jobs_source_sha256'), 'jobs', ['source_sha256'], unique=True)
    op.create_index(op.f('ix_jobs_state'), 'jobs', ['state'], unique=False)
    op.create_table('job_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_events_job_id'), 'job_events', ['job_id'], unique=False)
    op.create_index('ix_job_events_job_ts', 'job_events', ['job_id', 'ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_events_job_ts', table_name='job_events')
    op.drop_index(op.f('ix_job_events_job_id'), table_name='job_events')
    op.drop_table('job_events')
    op.drop_index(op.f('ix_jobs_state'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_source_sha256'), table_name='jobs')
    op.drop_index('ix_jobs_pending', table_name='jobs', postgresql_where=sa.text("state = 'pending'"))
    op.drop_table('jobs')
    # ### end Alembic commands ###
