"""voices for speaker enrollment

Revision ID: 543d12b24efb
Revises: fdc9754ed37e
Create Date: 2026-09-02 11:22:00.274381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '543d12b24efb'
down_revision: Union[str, Sequence[str], None] = 'fdc9754ed37e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=512), nullable=True),
    sa.Column('speech_s', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('dim > 0', name='ck_voices_dim'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voices_name'), 'voices', ['name'], unique=False)
    op.create_index('ix_voices_name_created', 'voices', ['name', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_voices_name_created', table_name='voices')
    op.drop_index(op.f('ix_voices_name'), table_name='voices')
    op.drop_table('voices')
    # ### end Alembic commands ###
