"""retry backoff via available_at

Revision ID: fdc9754ed37e
Revises: 4c453369a97a
Create Date: 2026-08-26 22:12:22.960698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc9754ed37e'
down_revision: Union[str, Sequence[str], None] = '4c453369a97a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('available_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_jobs_pending'), table_name='jobs', postgresql_where="((state)::text = 'pending'::text)")
    op.create_index('ix_jobs_pending', 'jobs', ['available_at', 'created_at'], unique=False, postgresql_where=sa.text("state = 'pending'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jobs_pending', table_name='jobs', postgresql_where=sa.text("state = 'pending'"))
    op.create_index(op.f('ix_jobs_pending'), 'jobs', ['created_at'], unique=False, postgresql_where="((state)::text = 'pending'::text)")
    op.drop_column('jobs', 'available_at')
    # ### end Alembic commands ###
